spring:
 security:
  oauth2:
   #client:
    #provider:
     #keycloak:
      #issuer-uri: http://localhost:9080/realms/myrealm
      #user-name-attribute: preferred_username
    #registration:
     #keycloak:
      #client-id: myclient      
      #authorization-grant-type: authorization_code # jwt-bearer | password | authorization_code
      #scope: openid
   resourceserver:
    jwt:
     issuer-uri: http://localhost:9080/realms/myrealm
     jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
 port: 8181